# Generated by Django 5.1.1 on 2024-11-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baño',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=100)),
                ('piso', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('mujer', 'Mujer'), ('hombre', 'Hombre'), ('neutro', 'Neutro'), ('discapacitado', 'Discapacitado')], max_length=20)),
                ('wc', models.IntegerField()),
                ('urinales', models.IntegerField(default=0)),
                ('dispensadores_jabon', models.IntegerField()),
                ('secador_o_papel', models.CharField(choices=[('papel', 'Papel'), ('secador', 'Secador')], max_length=10)),
                ('privacidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
