# Generated by Django 5.1.1 on 2024-11-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baño',
            name='numero',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
