# Generated by Django 5.1.1 on 2024-11-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_baño_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='baño',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='baño',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baño',
            name='secador_o_papel',
            field=models.CharField(choices=[('papel', 'Papel'), ('secador', 'Secador'), ('ambos', 'Ambos')], max_length=10),
        ),
    ]
